# Generated by Django 4.1.7 on 2023-03-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='achievements',
            new_name='role',
        ),
    ]
