# Generated by Django 4.1.7 on 2023-03-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp1', '0002_remove_movies_dtl_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies_dtl',
            name='pic',
            field=models.ImageField(default='default', upload_to='imgs'),
            preserve_default=False,
        ),
    ]
